encoder_name: 'tf_efficientnetv2_s_in21ft1k'
encoder_weights: 'infer'
in_features: 1280

chexpert_image_size: 256
chexpert_batch_size: 28      # orig: 28
chexpert_init_lr:    1.5e-4  # orig: 1.5e-4
chexpert_epochs:     7       # orig: 10

chest14_image_size: 256
chest14_batch_size: 28
chest14_init_lr: 0.0001
chest14_epochs: 15

aux_image_size: 256
aux_batch_size: 18      # orig 18
aux_init_lr: 1.0e-4       # orig 1e-4
aux_epochs: 20          # orig: 30
decoder: 'deeplabv3plus'
decoder_channels: 256
aux_mixup: False
aux_weight: 0.6
model_ema_decay: 0.997
