encoder_name: 'timm-efficientnet-b5'
encoder_weights: 'noisy-student'
in_features: 2048
workers: 2

chexpert_image_size: 512
chexpert_batch_size: 4  # orig: 28
chexpert_init_lr: 0.00015
chexpert_epochs: 10

chest14_image_size: 512
chest14_batch_size: 28
chest14_init_lr: 0.0001
chest14_epochs: 15

aux_image_size: 512
aux_batch_size: 8       # orig 18
aux_init_lr: 0.0001
aux_epochs: 30
decoder: 'deeplabv3plus'
decoder_channels: 256
aux_mixup: False
aux_weight: 0.6
model_ema_decay: 0.997
